"""empty message

Revision ID: 10705c63e7ff
Revises: 2ad212e40bbe
Create Date: 2026-07-20 02:53:17.049466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10705c63e7ff'
down_revision: Union[str, Sequence[str], None] = '2ad212e40bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('workload', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'workload')
    # ### end Alembic commands ###
