"""empty message

Revision ID: 56b9db7a5958
Revises: c38723a5b25e
Create Date: 2026-07-27 04:21:15.023737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56b9db7a5958'
down_revision: Union[str, Sequence[str], None] = 'c38723a5b25e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.Enum('PENDING', 'SHIPPED', 'COMPLETED', 'CANCELLED', name='orderstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
